version: '3.0'

services:
  jhipster-registry:
    image: jhipster/jhipster-registry:v6.0.2
    networks:
      - my-network
    volumes:
      - ./config:/config
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=test,swagger
      - SPRING_SECURITY_USER_PASSWORD=admin
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./config
    ports:
      - 8761:8761

  company:
    build: ../invest/company
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=test

  startup:
    build: ../invest/startup
    networks:
      - my-network
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=test

  user:
    build: ../invest/user
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=test

  communication:
    build: ../invest/communication
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=test

  shop:
    build: ../invest/shop
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=test
  ir:
    build: ../invest/ir
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=test
  board:
    build: ../invest/board
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=test
networks:
  my-network:
    name: my-network