version: '2.1'

services:
  jhipster-registry:
    image: jhipster/jhipster-registry:v6.0.2
    networks:
      - my-network
    volumes:
      - ./config:/config
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms512m
      - SPRING_PROFILES_ACTIVE=docker,swagger
      - SPRING_SECURITY_USER_PASSWORD=admin
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./config
    ports:
      - 8761:8761
  company:
    build: ./microservices/company
    mem_limit: 300m
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  startup:
    build: ./microservices/startup-composite
    mem_limit: 300m
    networks:
      - my-network
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  vc:
    build: ./microservices/vc-composite
    mem_limit: 300m
    networks:
      - my-network
    ports:
      - 8081:8081
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  user:
    build: ./microservices/user
    mem_limit: 300m
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  investment:
    build: ./microservices/investment
    mem_limit: 300m
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  board:
    build: ./microservices/board
    mem_limit: 300m
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  ir:
    build: ./microservices/ir
    mem_limit: 300m
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
networks:
  my-network:
    name: my-network