version: '2.1'

services:
  jhipster-registry:
    image: jhipster/jhipster-registry:v6.0.2
    volumes:
      - ./config:/config
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,swagger
      - SPRING_SECURITY_USER_PASSWORD=admin
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=./config/
    ports:
      - 8761:8761
    networks:
      - my-network


  gateway:
    build: cloud/gateway
    ports:
      - "8080:8080"
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=test

  company:
    build: microservices/company
    mem_limit: 350m
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=test

#  mysql:
#    image: mysql:5.7
#    networks:
#      - my-network
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=test1234
#      - MYSQL_DATABASE=invest
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=pwd
#
#  rabbitmq:
#    image: rabbitmq:3.7.8-management
#    networks:
#      - my-network
#    ports:
#      - 5672:5672
#      - 15672:15672
#    healthcheck:
#      test: ["CMD", "rabbitmqctl", "status"]
#      interval: 20s
#      timeout: 5s
#      retries: 10
#
#  zipkin:
#    image: openzipkin/zipkin:2.12.9
#    networks:
#      - my-network
#    environment:
#      - STORAGE_TYPE=mem
#      - RABBIT_ADDRESSES=rabbitmq
#    ports:
#      - 9411:9411
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
networks:
  my-network:
    name: my-network
