version: '2.1'

services:
  eureka:
    build: cloud/eureka-server
    ports:
      - "8761:8761"
    networks:
      - my-network
    #command: ["bash", "./wait-for-it.sh", "-t", "0", "config-server:8888", "--", "java", "-jar", "eureka-server.jar"]
    environment:
      - SPRING_PROFILES_ACTIVE=docker2
  config-server:
    build: cloud/config-server
    ports:
      - "8888:8888"
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker,native
networks:
  my-network:
    name: my-network