version: '2.1'

services:
  gateway:
    build: ./
    mem_limit: 300m
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=test
    ports:
      - 8080:8080
networks:
  my-network:
    name: my-network
