server.port: 7001

spring:
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mariadb://13.125.122.99:3306/invest_board
    username: root
    password: Illunex123!

logging.level:
  org.hibernate.SQL: debug

---
spring.profiles: test

spring:
  datasource:
    url: jdbc:mariadb://mariadb/invest_company
    username: root
    password: Illunex123!
  jpa:
    hibernate:
      ddl-auto: update