server.port: 7601

spring:
  datasource:
    url: jdbc:mariadb://13.124.193.64:3306/invest_communication
    username: root
    password: Illunex123!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  deevtools:
    livereload:
      enabled: true

logging.level:
  org.hibernate.SQL: debug

---
spring.profiles: docker
server.port: 8080

---
spring.profiles: test
server.port: 8080

spring:
  datasource:
    url: jdbc:mariadb://mariadb/invest_communication
    username: root
    password: Illunex123!
  jpa:
    hibernate:
      ddl-auto: update
