server.port: 7001

spring.jpa.hibernate.ddl-auto: update

spring.datasource:
  url: jdbc:mariadb://15.164.171.107:3306/invest_company
  username: effectmall
  password: effectmall@123

application.test: "test Message"
