server.port: 7101

spring:
  datasource:
    url: jdbc:mariadb://15.164.171.107:3306/invest_company
    username: effectmall
    password: effectmall@123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  deevtools:
    livereload:
      enabled: true

logging.level:
  org.hibernate.SQL: debug
---
spring.profiles: test

spring:
  datasource:
    url: jdbc:mariadb://mariadb/invest_company
    username: root
    password: Illunex123!
  jpa:
    hibernate:
      ddl-auto: create
