server.port: 7201

spring.jpa.hibernate.ddl-auto: update

spring:
  datasource:
    url: jdbc:mariadb://13.124.193.64:3306/invest
    username: root
    password: Illunex123!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  deevtools:
    livereload:
      enabled: true

logging.level:
  org.hibernate.SQL: debug
---
spring.profiles: test

spring:
  datasource:
    url: jdbc:mariadb://mariadb/invest
    username: root
    password: Illunex123!
  jpa:
    hibernate:
      ddl-auto: update