server.port: 7101

spring.jpa.hibernate.ddl-auto: update

spring:
  devtools:
    livereload:
      enabled: true

spring.datasource:
  url: jdbc:mariadb://15.164.171.107:3306/invest_investorrelations
  username: effectmall
  password: effectmall@123

application.test: "test Message"
