server.port: 7201

spring:
  datasource:
    url: jdbc:mariadb://15.164.212.141:3306/invest_investor_relations
    username: root
    password: Illunex123!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  deevtools:
    livereload:
      enabled: true

logging.level:
  org.hibernate.SQL: debug

---
spring.profiles: docker
---
spring.profiles: test

spring:
  datasource:
    url: jdbc:mariadb://mariadb/invest_investor_relations
    username: root
    password: Illunex123!
  jpa:
    hibernate:
      ddl-auto: update
