server.port: 7210

spring:
  datasource:
    url: jdbc:mariadb://13.125.122.99:3306/invest_user
    username: root
    password: Illunex123!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  deevtools:
    livereload:
      enabled: true

logging.level:
  org.hibernate.SQL: debug
---
spring.profiles: docker


---
spring.profiles: test

spring:
  datasource:
    url: jdbc:mariadb://13.125.122.99:3306/invest_company
    username: root
    password: Illunex123!
  jpa:
    hibernate:
      ddl-auto: update
