server.port: 7401

spring.jpa.hibernate.ddl-auto: update

spring:
  devtools:
    livereload:
      enabled: true

spring.datasource:
  url: jdbc:mariadb://15.164.171.107:3306/invest_user
  username: effectmall
  password: effectmall@123
