version: '2.1'

services:
  board:
    build: ./
    mem_limit: 300m
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=test
networks:
  my-network:
    name: my-network
